# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='content.proto',
  package='content',
  syntax='proto3',
  serialized_pb=_b('\n\rcontent.proto\x12\x07\x63ontent\x1a\nbase.proto\"U\n\x0b\x43ontentData\x12\x18\n\x02id\x18\x01 \x01(\x0b\x32\x0c.common.Uuid\x12\r\n\x05title\x18\x02 \x01(\t\x12\x1d\n\x07\x61uthors\x18\x03 \x03(\x0b\x32\x0c.common.Uuid\"_\n\x0b\x43ontentPart\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.content.ContentData\x12\x1e\n\x06\x66ormat\x18\x02 \x01(\x0e\x32\x0e.common.Format\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"R\n\x07\x43ontent\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.content.ContentData\x12#\n\x05parts\x18\x02 \x03(\x0b\x32\x14.content.ContentPart\"F\n\x0b\x43mdResponse\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x1c\n\x05level\x18\x02 \x01(\x0e\x32\r.common.Level\x12\x0b\n\x03msg\x18\x03 \x01(\t\"B\n\nUpdatePart\x12\"\n\x04part\x18\x01 \x01(\x0b\x32\x14.content.ContentPart\x12\x10\n\x08position\x18\x02 \x01(\r2\xe4\x01\n\x11\x43ontentCmdHandler\x12\x30\n\x04save\x12\x10.content.Content\x1a\x14.content.CmdResponse\"\x00\x12.\n\x06remove\x12\x0c.common.Uuid\x1a\x14.content.CmdResponse\"\x00\x12\x32\n\nremovePart\x12\x0c.common.Uuid\x1a\x14.content.CmdResponse\"\x00\x12\x39\n\nupdatePart\x12\x13.content.UpdatePart\x1a\x14.content.CmdResponse\"\x00\x42\x03\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[base__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTENTDATA = _descriptor.Descriptor(
  name='ContentData',
  full_name='content.ContentData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='content.ContentData.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='content.ContentData.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authors', full_name='content.ContentData.authors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=123,
)


_CONTENTPART = _descriptor.Descriptor(
  name='ContentPart',
  full_name='content.ContentPart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='content.ContentPart.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='content.ContentPart.format', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='content.ContentPart.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=220,
)


_CONTENT = _descriptor.Descriptor(
  name='Content',
  full_name='content.Content',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='content.Content.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parts', full_name='content.Content.parts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=304,
)


_CMDRESPONSE = _descriptor.Descriptor(
  name='CmdResponse',
  full_name='content.CmdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='content.CmdResponse.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='content.CmdResponse.level', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='content.CmdResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=376,
)


_UPDATEPART = _descriptor.Descriptor(
  name='UpdatePart',
  full_name='content.UpdatePart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='part', full_name='content.UpdatePart.part', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='content.UpdatePart.position', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=444,
)

_CONTENTDATA.fields_by_name['id'].message_type = base__pb2._UUID
_CONTENTDATA.fields_by_name['authors'].message_type = base__pb2._UUID
_CONTENTPART.fields_by_name['info'].message_type = _CONTENTDATA
_CONTENTPART.fields_by_name['format'].enum_type = base__pb2._FORMAT
_CONTENT.fields_by_name['info'].message_type = _CONTENTDATA
_CONTENT.fields_by_name['parts'].message_type = _CONTENTPART
_CMDRESPONSE.fields_by_name['level'].enum_type = base__pb2._LEVEL
_UPDATEPART.fields_by_name['part'].message_type = _CONTENTPART
DESCRIPTOR.message_types_by_name['ContentData'] = _CONTENTDATA
DESCRIPTOR.message_types_by_name['ContentPart'] = _CONTENTPART
DESCRIPTOR.message_types_by_name['Content'] = _CONTENT
DESCRIPTOR.message_types_by_name['CmdResponse'] = _CMDRESPONSE
DESCRIPTOR.message_types_by_name['UpdatePart'] = _UPDATEPART

ContentData = _reflection.GeneratedProtocolMessageType('ContentData', (_message.Message,), dict(
  DESCRIPTOR = _CONTENTDATA,
  __module__ = 'content_pb2'
  # @@protoc_insertion_point(class_scope:content.ContentData)
  ))
_sym_db.RegisterMessage(ContentData)

ContentPart = _reflection.GeneratedProtocolMessageType('ContentPart', (_message.Message,), dict(
  DESCRIPTOR = _CONTENTPART,
  __module__ = 'content_pb2'
  # @@protoc_insertion_point(class_scope:content.ContentPart)
  ))
_sym_db.RegisterMessage(ContentPart)

Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), dict(
  DESCRIPTOR = _CONTENT,
  __module__ = 'content_pb2'
  # @@protoc_insertion_point(class_scope:content.Content)
  ))
_sym_db.RegisterMessage(Content)

CmdResponse = _reflection.GeneratedProtocolMessageType('CmdResponse', (_message.Message,), dict(
  DESCRIPTOR = _CMDRESPONSE,
  __module__ = 'content_pb2'
  # @@protoc_insertion_point(class_scope:content.CmdResponse)
  ))
_sym_db.RegisterMessage(CmdResponse)

UpdatePart = _reflection.GeneratedProtocolMessageType('UpdatePart', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEPART,
  __module__ = 'content_pb2'
  # @@protoc_insertion_point(class_scope:content.UpdatePart)
  ))
_sym_db.RegisterMessage(UpdatePart)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\370\001\001'))
import abc
from grpc.early_adopter import implementations
from grpc.framework.alpha import utilities
class EarlyAdopterContentCmdHandlerServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def save(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def remove(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def removePart(self, request, context):
    raise NotImplementedError()
  @abc.abstractmethod
  def updatePart(self, request, context):
    raise NotImplementedError()
class EarlyAdopterContentCmdHandlerServer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def start(self):
    raise NotImplementedError()
  @abc.abstractmethod
  def stop(self):
    raise NotImplementedError()
class EarlyAdopterContentCmdHandlerStub(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def save(self, request):
    raise NotImplementedError()
  save.async = None
  @abc.abstractmethod
  def remove(self, request):
    raise NotImplementedError()
  remove.async = None
  @abc.abstractmethod
  def removePart(self, request):
    raise NotImplementedError()
  removePart.async = None
  @abc.abstractmethod
  def updatePart(self, request):
    raise NotImplementedError()
  updatePart.async = None
def early_adopter_create_ContentCmdHandler_server(servicer, port, private_key=None, certificate_chain=None):
  import content_pb2
  import content_pb2
  import base_pb2
  import content_pb2
  import base_pb2
  import content_pb2
  import content_pb2
  import content_pb2
  method_service_descriptions = {
    "remove": utilities.unary_unary_service_description(
      servicer.remove,
      base_pb2.Uuid.FromString,
      content_pb2.CmdResponse.SerializeToString,
    ),
    "removePart": utilities.unary_unary_service_description(
      servicer.removePart,
      base_pb2.Uuid.FromString,
      content_pb2.CmdResponse.SerializeToString,
    ),
    "save": utilities.unary_unary_service_description(
      servicer.save,
      content_pb2.Content.FromString,
      content_pb2.CmdResponse.SerializeToString,
    ),
    "updatePart": utilities.unary_unary_service_description(
      servicer.updatePart,
      content_pb2.UpdatePart.FromString,
      content_pb2.CmdResponse.SerializeToString,
    ),
  }
  return implementations.server("content.ContentCmdHandler", method_service_descriptions, port, private_key=private_key, certificate_chain=certificate_chain)
def early_adopter_create_ContentCmdHandler_stub(host, port, metadata_transformer=None, secure=False, root_certificates=None, private_key=None, certificate_chain=None, server_host_override=None):
  import content_pb2
  import content_pb2
  import base_pb2
  import content_pb2
  import base_pb2
  import content_pb2
  import content_pb2
  import content_pb2
  method_invocation_descriptions = {
    "remove": utilities.unary_unary_invocation_description(
      base_pb2.Uuid.SerializeToString,
      content_pb2.CmdResponse.FromString,
    ),
    "removePart": utilities.unary_unary_invocation_description(
      base_pb2.Uuid.SerializeToString,
      content_pb2.CmdResponse.FromString,
    ),
    "save": utilities.unary_unary_invocation_description(
      content_pb2.Content.SerializeToString,
      content_pb2.CmdResponse.FromString,
    ),
    "updatePart": utilities.unary_unary_invocation_description(
      content_pb2.UpdatePart.SerializeToString,
      content_pb2.CmdResponse.FromString,
    ),
  }
  return implementations.stub("content.ContentCmdHandler", method_invocation_descriptions, host, port, metadata_transformer=metadata_transformer, secure=secure, root_certificates=root_certificates, private_key=private_key, certificate_chain=certificate_chain, server_host_override=server_host_override)
# @@protoc_insertion_point(module_scope)
